"use client";

import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "@lib/api";
import { Card, CardContent } from "@components/ui/card";
import { Button } from "@components/ui/button";
import { Input } from "@components/ui/input";
import { Badge } from "@components/ui/badge";
import { Skeleton } from "@components/ui/skeleton";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@components/ui/tabs";
import { z } from "zod";
import { formatRelativeDate, formatCurrency, absoluteUrl } from "@lib/utils";
import {
  Link2, MousePointerClick, DollarSign, TrendingUp, Copy, Check,
  UserCheck, Clock, XCircle, Send, PlusCircle, Trash2, Save,
  Monitor, Calendar, Download, Wallet, User, CreditCard,
  BarChart3, History, Plus, Banknote, Shield,
} from "lucide-react";
import Link from "next/link";

interface Platform { name: string; url: string }

interface Application {
  id: string; status: string; platforms: Platform[];
  fullName?: string; phone?: string; country?: string;
  paypalEmail?: string; cryptoType?: string; cryptoAddress?: string;
  cryptoNetwork?: string; contactForPayment?: boolean;
  note?: string; adminNote?: string; maxManualLinks: number;
  approvedAt?: string; createdAt: string;
}

interface AffiliateLink {
  id: string; code: string; commissionRate: number;
  totalClicks: number; totalConversions: number; totalEarned: number;
  isActive: boolean; isAutoGenerated: boolean; createdAt: string;
}

interface AffiliateLevel { name: string; level: number; commissionRate: number }

interface AffiliateStats {
  totalLinks: number; totalClicks: number; totalConversions: number; totalEarned: number;
  affiliateLevel: AffiliateLevel | null;
  links: AffiliateLink[];
}

interface Withdrawal {
  id: string; amount: number; status: string;
  paymentMethod: string | null; paymentDetails: string | null;
  adminNote: string | null; processedAt: string | null; createdAt: string;
}

const platformSchema = z.object({
  name: z.string().min(1, "اسم المنصة مطلوب").max(100),
  url: z.string().url("رابط غير صالح").max(500),
});
const applySchema = z.object({
  platforms: z.array(platformSchema).min(1, "أضف منصة واحدة على الأقل"),
  fullName: z.string().max(200).optional(),
  phone: z.string().max(50).optional(),
  country: z.string().max(100).optional(),
  paypalEmail: z.string().email("إيميل PayPal غير صالح").optional(),
  cryptoType: z.enum(["USDT", "USDC", "BTC"]).optional(),
  cryptoAddress: z.string().max(255).optional(),
  cryptoNetwork: z.string().max(20).optional(),
  contactForPayment: z.boolean().optional(),
  note: z.string().max(1000).optional(),
});
type ApplyForm = z.infer<typeof applySchema>;

const statCards = [
  { key: "totalLinks", label: "إجمالي الروابط", icon: Link2, color: "text-blue-600 bg-blue-100 dark:bg-blue-900/30" },
  { key: "totalClicks", label: "إجمالي النقرات", icon: MousePointerClick, color: "text-purple-600 bg-purple-100 dark:bg-purple-900/30" },
  { key: "totalConversions", label: "إجمالي التحويلات", icon: TrendingUp, color: "text-emerald-600 bg-emerald-100 dark:bg-emerald-900/30" },
  { key: "totalEarned", label: "إجمالي الأرباح", icon: DollarSign, color: "text-amber-600 bg-amber-100 dark:bg-amber-900/30" },
];

const statusBadge: Record<string, { label: string; color: string }> = {
  PENDING: { label: "قيد الانتظار", color: "bg-amber-100 text-amber-700 border-amber-200" },
  APPROVED: { label: "تمت الموافقة", color: "bg-emerald-100 text-emerald-700 border-emerald-200" },
  REJECTED: { label: "مرفوض", color: "bg-red-100 text-red-700 border-red-200" },
};

const paymentMethods = [
  { id: "paypal", label: "PayPal", icon: CreditCard },
  { id: "crypto", label: "عملات رقمية", icon: Banknote },
  { id: "bank", label: "تحويل بنكي", icon: Banknote },
  { id: "contact", label: "تواصل معنا", icon: User },
];

export default function AffiliatesPage() {
  const queryClient = useQueryClient();
  const [tab, setTab] = useState("overview");
  const [copiedCode, setCopiedCode] = useState<string | null>(null);
  const [platforms, setPlatforms] = useState<Platform[]>([]);

  const { data: statsResp, isLoading: statsLoading } = useQuery({
    queryKey: ["affiliates", "stats"],
    queryFn: () => api.get<{ data: AffiliateStats }>("/affiliates/stats"),
  });

  const { data: appResp, isLoading: appLoading } = useQuery({
    queryKey: ["affiliates", "application"],
    queryFn: () => api.get<{ data: Application | null }>("/affiliates/application"),
  });

  const { data: withdrawalsResp } = useQuery({
    queryKey: ["affiliates", "withdrawals"],
    queryFn: () => api.get<{ data: Withdrawal[] }>("/affiliates/withdrawals"),
  });

  const stats = statsResp?.data;
  const application = appResp?.data;
  const withdrawals = withdrawalsResp?.data;
  const isLoading = statsLoading || appLoading;

  const applyMutation = useMutation({
    mutationFn: (body: ApplyForm) => api.post("/affiliates/apply", body),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["affiliates", "application"] }),
    onError: (err) => console.error("Apply error:", err),
  });

  const paymentMutation = useMutation({
    mutationFn: (body: Record<string, unknown>) => api.patch("/affiliates/application/payment", body),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["affiliates", "application"] }),
    onError: (err) => console.error("Payment update error:", err),
  });

  const copyToClipboard = async (text: string) => {
    try { await navigator.clipboard.writeText(text); setCopiedCode(text); setTimeout(() => setCopiedCode(null), 2000); } catch {}
  };

  const onApply = (data: ApplyForm) => applyMutation.mutate(data);
  const addPlatform = () => setPlatforms([...platforms, { name: "", url: "" }]);
  const removePlatform = (index: number) => setPlatforms(platforms.filter((_, i) => i !== index));
  const updatePlatform = (index: number, field: "name" | "url", value: string) => {
    const updated = [...platforms]; updated[index] = { ...updated[index], [field]: value }; setPlatforms(updated);
  };

  const totalEarned = stats?.totalEarned ?? 0;
  const totalWithdrawn = (withdrawals ?? []).filter((w) => w.status === "APPROVED").reduce((s, w) => s + w.amount, 0);
  const pendingAmount = (withdrawals ?? []).filter((w) => w.status === "PENDING").reduce((s, w) => s + w.amount, 0);
  const available = Math.max(0, totalEarned - totalWithdrawn - pendingAmount);
  const autoLink = stats?.links?.find((l) => l.isAutoGenerated);

  if (isLoading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-8 w-48" />
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {[1, 2, 3, 4].map((i) => (<Card key={i}><CardContent className="p-6"><Skeleton className="h-12 w-12 rounded-lg" /><Skeleton className="h-6 w-16 mt-2" /><Skeleton className="h-4 w-24 mt-1" /></CardContent></Card>))}
        </div>
      </div>
    );
  }

  if (!application) {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h1 className="text-3xl font-bold tracking-tight">برنامج العمولة</h1>
          <Link href="/admin/affiliates" className="flex items-center gap-1.5 text-sm text-primary hover:underline">
            <Shield className="h-4 w-4" /> إدارة المسوقين
          </Link>
        </div>
        <ApplySection platforms={platforms} addPlatform={addPlatform} removePlatform={removePlatform} updatePlatform={updatePlatform} onSubmit={onApply} isPending={applyMutation.isPending} />
      </div>
    );
  }

  if (application.status === "pending") {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h1 className="text-3xl font-bold tracking-tight">برنامج العمولة</h1>
          <Link href="/admin/affiliates" className="flex items-center gap-1.5 text-sm text-primary hover:underline">
            <Shield className="h-4 w-4" /> إدارة المسوقين
          </Link>
        </div>
        <PendingApplication app={application} onUpdatePayment={(d) => paymentMutation.mutate(d)} isPending={paymentMutation.isPending} />
      </div>
    );
  }

  if (application.status === "rejected") {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h1 className="text-3xl font-bold tracking-tight">برنامج العمولة</h1>
          <Link href="/admin/affiliates" className="flex items-center gap-1.5 text-sm text-primary hover:underline">
            <Shield className="h-4 w-4" /> إدارة المسوقين
          </Link>
        </div>
        <RejectedApplication app={application} onUpdatePayment={(d) => paymentMutation.mutate(d)} isPending={paymentMutation.isPending} onReapply={() => window.location.reload()} />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold tracking-tight">برنامج العمولة</h1>
        <Link href="/admin/affiliates" className="flex items-center gap-1.5 text-sm text-primary hover:underline">
          <Shield className="h-4 w-4" /> إدارة المسوقين
        </Link>
      </div>

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList className="w-full flex-wrap h-auto">
          <TabsTrigger value="overview"><BarChart3 className="h-4 w-4 ml-2" />الرئيسية</TabsTrigger>
          <TabsTrigger value="myinfo"><User className="h-4 w-4 ml-2" />بياناتي</TabsTrigger>
          <TabsTrigger value="payments"><Wallet className="h-4 w-4 ml-2" />المدفوعات</TabsTrigger>
          <TabsTrigger value="payment-info"><CreditCard className="h-4 w-4 ml-2" />معلومات الدفع</TabsTrigger>
          <TabsTrigger value="reports"><TrendingUp className="h-4 w-4 ml-2" />التقارير</TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="mt-6 space-y-6">
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {statCards.map((stat) => {
              const Icon = stat.icon;
              const value = stats ? stats[stat.key as keyof AffiliateStats] : 0;
              return (
                <Card key={stat.key}>
                  <CardContent className="p-6 flex items-center gap-4">
                    <div className={`h-12 w-12 rounded-lg flex items-center justify-center shrink-0 ${stat.color}`}>
                      <Icon className="h-6 w-6" />
                    </div>
                    <div className="min-w-0">
                      <p className="text-2xl font-bold">{stat.key === "totalEarned" ? formatCurrency(value as number, "USD") : String(value)}</p>
                      <p className="text-sm text-muted-foreground truncate">{stat.label}</p>
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>

          <AutoGeneratedLink links={stats?.links ?? []} copyToClipboard={copyToClipboard} copiedCode={copiedCode} />
        </TabsContent>

        <TabsContent value="myinfo" className="mt-6 space-y-4">
          <Card>
            <CardContent className="p-6">
              <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <User className="h-5 w-5 text-primary" />
                بيانات المسوق
              </h2>
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <InfoItem label="الاسم" value={application.fullName || "—"} />
                <InfoItem label="البريد الإلكتروني" value={application.fullName ? "—" : "—"} />
                <InfoItem label="البلد" value={application.country || "—"} />
                <InfoItem label="رقم التلفون" value={application.phone || "—"} />
                <InfoItem label="الكود التابع" value={autoLink?.code || "—"} />
                <InfoItem label="نسبة العمولة" value={stats?.affiliateLevel ? `${Number(stats.affiliateLevel.commissionRate) * 100}%` : autoLink ? `${Number(autoLink.commissionRate) * 100}%` : "—"} />
                <InfoItem label="المستوى" value={stats?.affiliateLevel?.name || "—"} />
                <InfoItem label="إجمالي الأرباح" value={formatCurrency(totalEarned, "USD")} />
                <InfoItem label="إجمالي المسحوبات" value={formatCurrency(totalWithdrawn, "USD")} />
                <InfoItem label="إجمالي النقرات" value={String(stats?.totalClicks ?? 0)} />
                <InfoItem label="إجمالي التحويلات" value={String(stats?.totalConversions ?? 0)} />
                <InfoItem label="الرصيد المتاح" value={formatCurrency(available, "USD")} />
              </div>
            </CardContent>
          </Card>

          {Array.isArray(application.platforms) && application.platforms.length > 0 && (
            <Card>
              <CardContent className="p-6">
                <h3 className="text-sm font-semibold mb-3">المنصات</h3>
                <div className="space-y-2">
                  {application.platforms.map((p, i) => (
                    <div key={i} className="text-sm flex gap-2">
                      <span className="font-medium">{p.name}:</span>
                      <span className="text-muted-foreground font-mono text-xs truncate" dir="ltr">{p.url}</span>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}
        </TabsContent>

        <TabsContent value="payments" className="mt-6 space-y-6">
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <PaymentCard icon={DollarSign} value={formatCurrency(totalEarned, "USD")} label="إجمالي الأرباح" color="text-emerald-600 bg-emerald-100 dark:bg-emerald-900/30" />
            <PaymentCard icon={Wallet} value={formatCurrency(available, "USD")} label="الرصيد المتاح للسحب" color="text-blue-600 bg-blue-100 dark:bg-blue-900/30" />
            <PaymentCard icon={Clock} value={formatCurrency(pendingAmount, "USD")} label="قيد الانتظار" color="text-amber-600 bg-amber-100 dark:bg-amber-900/30" />
            <PaymentCard icon={History} value={formatCurrency(totalWithdrawn, "USD")} label="إجمالي المسحوبات" color="text-purple-600 bg-purple-100 dark:bg-purple-900/30" />
          </div>

          <WithdrawalRequestSection available={available} onSuccess={() => queryClient.invalidateQueries({ queryKey: ["affiliates", "withdrawals"] })} />

          <Card>
            <CardContent className="p-6">
              <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <History className="h-5 w-5 text-muted-foreground" />
                سجل السحوبات
              </h3>
              {withdrawals && withdrawals.length > 0 ? (
                <div className="divide-y">
                  {withdrawals.map((w) => {
                    const badge = statusBadge[w.status] || statusBadge.PENDING;
                    return (
                      <div key={w.id} className="py-3 flex items-center justify-between gap-4">
                        <div className="min-w-0">
                          <p className="font-semibold">{formatCurrency(w.amount, "USD")}</p>
                          <p className="text-xs text-muted-foreground">
                            {w.paymentMethod && `${w.paymentMethod}`}{w.paymentMethod && w.paymentDetails && " — "}{w.paymentDetails}
                          </p>
                          <p className="text-xs text-muted-foreground">{formatRelativeDate(w.createdAt)}</p>
                          {w.adminNote && <p className="text-xs text-muted-foreground mt-1">ملاحظة: {w.adminNote}</p>}
                        </div>
                        <span className={`shrink-0 text-xs px-2.5 py-1 rounded-full border ${badge.color}`}>{badge.label}</span>
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className="text-center py-8 text-muted-foreground">
                  <History className="h-10 w-10 mx-auto mb-2 opacity-50" />
                  <p className="text-sm">لا توجد طلبات سحب حتى الآن</p>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="payment-info" className="mt-6 space-y-4">
          <Card>
            <CardContent className="p-6">
              <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <CreditCard className="h-5 w-5 text-primary" />
                وسائل الدفع
              </h2>
              <PaymentMethodsForm
                paypalEmail={application.paypalEmail}
                cryptoType={application.cryptoType}
                cryptoAddress={application.cryptoAddress}
                cryptoNetwork={application.cryptoNetwork}
                contactForPayment={application.contactForPayment}
                onSave={(d) => paymentMutation.mutate(d)}
                isPending={paymentMutation.isPending}
              />
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6 space-y-4">
              <h3 className="text-lg font-semibold flex items-center gap-2">
                <DollarSign className="h-5 w-5 text-muted-foreground" />
                إعدادات السحب
              </h3>
              <InfoItem label="العملة" value="USD" />
              <InfoItem label="الحد الأدنى للسحب" value="$5.00" />
              <InfoItem label="حالة الرصيد" value={`${formatCurrency(available, "USD")} متاح`} />
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
                <Calendar className="h-5 w-5 text-muted-foreground" />
                جدول الدفع
              </h3>
              <div className="text-sm text-muted-foreground space-y-2">
                <p>• يتم معالجة طلبات السحب حسب جدول زمني منتظم.</p>
                <p>• بعد تقديم الطلب، نبدأ عملية حجز مؤقت للتحقق من حركة المرور.</p>
                <p>• يتم تحويل المدفوعات في دورة الدفع التالية بعد التحقق.</p>
                <p>• الحد الأدنى للسحب يبدأ من $5.</p>
                <p>• طرق الدفع المتاحة: PayPal، عملات رقمية (USDT/BTC)، تحويل بنكي.</p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="reports" className="mt-6">
          <ReportsSection links={stats?.links ?? []} />
        </TabsContent>
      </Tabs>
    </div>
  );
}

function InfoItem({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="text-sm font-medium">{value}</p>
    </div>
  );
}

function PaymentCard({ icon: Icon, value, label, color }: { icon: any; value: string; label: string; color: string }) {
  return (
    <Card>
      <CardContent className="p-5 flex items-center gap-3">
        <div className={`h-10 w-10 rounded-lg flex items-center justify-center shrink-0 ${color}`}>
          <Icon className="h-5 w-5" />
        </div>
        <div className="min-w-0">
          <p className="text-lg font-bold">{value}</p>
          <p className="text-xs text-muted-foreground truncate">{label}</p>
        </div>
      </CardContent>
    </Card>
  );
}

function WithdrawalRequestSection({ available, onSuccess }: { available: number; onSuccess: () => void }) {
  const [showForm, setShowForm] = useState(false);
  const [amount, setAmount] = useState("");
  const [paymentMethod, setPaymentMethod] = useState("");
  const [paymentDetails, setPaymentDetails] = useState("");
  const [error, setError] = useState("");

  const mutation = useMutation({
    mutationFn: (body: { amount: number; paymentMethod?: string; paymentDetails?: string }) =>
      api.post("/affiliates/withdrawals", body),
    onSuccess: () => { onSuccess(); setShowForm(false); setAmount(""); setPaymentMethod(""); setPaymentDetails(""); setError(""); },
    onError: (err: any) => setError(err?.message || "حدث خطأ"),
  });

  const handleSubmit = () => {
    const num = parseFloat(amount);
    if (isNaN(num) || num <= 0) { setError("أدخل مبلغ صحيح"); return; }
    if (num > available) { setError("المبلغ يتجاوز الرصيد المتاح"); return; }
    mutation.mutate({ amount: num, paymentMethod: paymentMethod || undefined, paymentDetails: paymentDetails || undefined });
  };

  if (!showForm) {
    return (
      <Card>
        <CardContent className="p-6 text-center">
          <Wallet className="h-12 w-12 text-muted-foreground mx-auto mb-3" />
          <h3 className="text-lg font-semibold mb-1">طلب سحب جديد</h3>
          <p className="text-sm text-muted-foreground mb-4">رصيدك المتاح للسحب هو {formatCurrency(available, "USD")}</p>
          <Button onClick={() => setShowForm(true)} disabled={available <= 0}>
            <Plus className="h-4 w-4 ml-2" /> إنشاء طلب سحب
          </Button>
          {available <= 0 && <p className="text-xs text-muted-foreground mt-2">لا يوجد رصيد متاح للسحب حالياً</p>}
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardContent className="p-6 space-y-4">
        <h3 className="text-lg font-semibold">طلب سحب جديد</h3>
        <p className="text-sm text-muted-foreground">الرصيد المتاح: {formatCurrency(available, "USD")}</p>
        <div>
          <label className="text-sm mb-1 block font-medium">المبلغ</label>
          <div className="flex gap-2">
            <Input type="number" min="1" step="0.01" placeholder="0.00" value={amount} dir="ltr" onChange={(e) => setAmount(e.target.value)} className="max-w-48" />
            <span className="flex items-center text-sm text-muted-foreground">USD</span>
          </div>
        </div>
        <div>
          <label className="text-sm mb-1 block font-medium">طريقة الدفع</label>
          <div className="grid gap-2 sm:grid-cols-2">
            {paymentMethods.map((pm) => {
              const Icon = pm.icon;
              return (
                <button key={pm.id} onClick={() => setPaymentMethod(pm.label)}
                  className={`flex items-center gap-3 p-3 rounded-md border text-right transition-colors ${paymentMethod === pm.label ? "border-primary bg-primary/5" : "border-input hover:border-primary/50"}`}>
                  <Icon className="h-5 w-5 text-muted-foreground shrink-0" />
                  <span className="text-sm">{pm.label}</span>
                  {paymentMethod === pm.label && <Check className="h-4 w-4 text-primary mr-auto" />}
                </button>
              );
            })}
          </div>
        </div>
        <div>
          <label className="text-sm mb-1 block font-medium">تفاصيل الدفع (اختياري)</label>
          <Input placeholder="إيميل PayPal، عنوان المحفظة..." value={paymentDetails} dir="ltr" onChange={(e) => setPaymentDetails(e.target.value)} />
        </div>
        {error && <p className="text-sm text-destructive">{error}</p>}
        <div className="flex gap-2">
          <Button onClick={handleSubmit} disabled={mutation.isPending || !amount || parseFloat(amount) > available}>
            {mutation.isPending ? "جارٍ الإرسال..." : "تقديم الطلب"}
          </Button>
          <Button variant="outline" onClick={() => setShowForm(false)}>إلغاء</Button>
        </div>
      </CardContent>
    </Card>
  );
}

const networks: Record<string, string[]> = {
  USDT: ["TRC20", "ERC20", "BEP20", "SOL"],
  USDC: ["ERC20", "BEP20", "SOL"],
  BTC: ["BTC"],
};

function PaymentMethodsForm({
  paypalEmail: initialPaypal, cryptoType: initialCrypto, cryptoAddress: initialAddress,
  cryptoNetwork: initialNetwork, contactForPayment: initialContact,
  onSave, isPending, compact,
}: {
  paypalEmail?: string; cryptoType?: string; cryptoAddress?: string;
  cryptoNetwork?: string; contactForPayment?: boolean;
  onSave: (d: Record<string, unknown>) => void; isPending: boolean; compact?: boolean;
}) {
  const [usePaypal, setUsePaypal] = useState(!!initialPaypal);
  const [useCrypto, setUseCrypto] = useState(!!initialCrypto);
  const [useContact, setUseContact] = useState(!!initialContact);
  const [paypalEmail, setPaypalEmail] = useState(initialPaypal || "");
  const [cryptoType, setCryptoType] = useState(initialCrypto || "");
  const [cryptoAddress, setCryptoAddress] = useState(initialAddress || "");
  const [cryptoNetwork, setCryptoNetwork] = useState(initialNetwork || "");
  const [error, setError] = useState("");

  const handleSave = () => {
    setError("");
    if (!usePaypal && !useCrypto && !useContact) { setError("اختر على الأقل وسيلة دفع واحدة"); return; }
    if (usePaypal && !paypalEmail) { setError("أدخل إيميل PayPal"); return; }
    if (useCrypto && (!cryptoType || !cryptoAddress || !cryptoNetwork)) { setError("أكمل بيانات العملة الرقمية"); return; }
    const data: Record<string, unknown> = {};
    if (usePaypal) data.paypalEmail = paypalEmail; else data.paypalEmail = null;
    if (useCrypto) { data.cryptoType = cryptoType; data.cryptoAddress = cryptoAddress; data.cryptoNetwork = cryptoNetwork; }
    else { data.cryptoType = null; data.cryptoAddress = null; data.cryptoNetwork = null; }
    data.contactForPayment = useContact;
    onSave(data);
  };

  return (
    <div className={`space-y-4 ${compact ? "" : ""}`}>
      <div className="flex flex-wrap gap-4">
        <label className="flex items-center gap-2 cursor-pointer">
          <input type="checkbox" checked={usePaypal} onChange={(e) => setUsePaypal(e.target.checked)} className="h-4 w-4" />
          <span className="text-sm">PayPal</span>
        </label>
        <label className="flex items-center gap-2 cursor-pointer">
          <input type="checkbox" checked={useCrypto} onChange={(e) => setUseCrypto(e.target.checked)} className="h-4 w-4" />
          <span className="text-sm">عملات رقمية</span>
        </label>
        <label className="flex items-center gap-2 cursor-pointer">
          <input type="checkbox" checked={useContact} onChange={(e) => setUseContact(e.target.checked)} className="h-4 w-4" />
          <span className="text-sm">تواصل معنا</span>
        </label>
      </div>

      {usePaypal && (
        <div>
          <label className="text-sm mb-1 block">إيميل PayPal</label>
          <Input placeholder="your@email.com" value={paypalEmail} dir="ltr" onChange={(e) => setPaypalEmail(e.target.value)} />
        </div>
      )}

      {useCrypto && (
        <div className="space-y-3">
          <div className="grid gap-3 sm:grid-cols-3">
            <div>
              <label className="text-sm mb-1 block">العملة</label>
              <select className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={cryptoType} onChange={(e) => { setCryptoType(e.target.value); setCryptoNetwork("") }}>
                <option value="">-- اختر --</option>
                <option value="USDT">USDT</option>
                <option value="USDC">USDC</option>
                <option value="BTC">BTC</option>
              </select>
            </div>
            <div>
              <label className="text-sm mb-1 block">الشبكة</label>
              <select className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={cryptoNetwork} onChange={(e) => setCryptoNetwork(e.target.value)} disabled={!cryptoType}>
                <option value="">-- اختر --</option>
                {cryptoType && networks[cryptoType]?.map((n) => (<option key={n} value={n}>{n}</option>))}
              </select>
            </div>
            <div>
              <label className="text-sm mb-1 block">عنوان المحفظة</label>
              <Input placeholder={cryptoType === "BTC" ? "bc1..." : "0x..."} value={cryptoAddress} dir="ltr" onChange={(e) => setCryptoAddress(e.target.value)} />
            </div>
          </div>
        </div>
      )}

      {useContact && <p className="text-sm text-muted-foreground">سيتم التواصل معك لترتيب وسيلة الدفع المناسبة</p>}
      {error && <p className="text-sm text-destructive">{error}</p>}
      <Button onClick={handleSave} disabled={isPending} size="sm" variant="outline">
        <Save className="h-4 w-4 ml-2" />{isPending ? "جارٍ الحفظ..." : "حفظ"}
      </Button>
    </div>
  );
}

function ApplySection({ platforms, addPlatform, removePlatform, updatePlatform, onSubmit, isPending }: {
  platforms: Platform[]; addPlatform: () => void; removePlatform: (i: number) => void;
  updatePlatform: (i: number, f: "name" | "url", v: string) => void;
  onSubmit: (d: ApplyForm) => void; isPending: boolean;
}) {
  const [fullName, setFullName] = useState("");
  const [phone, setPhone] = useState("");
  const [country, setCountry] = useState("");
  const [usePaypal, setUsePaypal] = useState(true);
  const [useCrypto, setUseCrypto] = useState(false);
  const [useContact, setUseContact] = useState(false);
  const [paypalEmail, setPaypalEmail] = useState("");
  const [cryptoType, setCryptoType] = useState("");
  const [cryptoAddress, setCryptoAddress] = useState("");
  const [cryptoNetwork, setCryptoNetwork] = useState("");
  const [note, setNote] = useState("");
  const [error, setError] = useState("");

  const handleSubmit = () => {
    setError("");
    if (platforms.length === 0 || !platforms[0].name) { setError("أضف منصة واحدة على الأقل"); return; }
    if (!usePaypal && !useCrypto && !useContact) { setError("اختر على الأقل وسيلة دفع واحدة"); return; }
    if (usePaypal && !paypalEmail) { setError("أدخل إيميل PayPal"); return; }
    if (useCrypto && (!cryptoType || !cryptoAddress || !cryptoNetwork)) { setError("أكمل بيانات العملة الرقمية"); return; }
    onSubmit({
      platforms: platforms.filter((p) => p.name && p.url),
      ...(fullName ? { fullName } : {}), ...(phone ? { phone } : {}), ...(country ? { country } : {}),
      ...(usePaypal && paypalEmail ? { paypalEmail } : {}),
      ...(useCrypto && cryptoType ? { cryptoType: cryptoType as "USDT" | "USDC" | "BTC" } : {}),
      ...(useCrypto && cryptoAddress ? { cryptoAddress } : {}), ...(useCrypto && cryptoNetwork ? { cryptoNetwork } : {}),
      contactForPayment: useContact, ...(note ? { note } : {}),
    });
  };

  return (
    <Card className="border-primary/20">
      <CardContent className="p-6 space-y-6">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
            <UserCheck className="h-5 w-5 text-primary" />
          </div>
          <div>
            <h2 className="text-xl font-semibold">انضم لبرنامج العمولة</h2>
            <p className="text-sm text-muted-foreground">احصل على رابطك التابع وابدأ الربح من خلال الترويج للموقع</p>
          </div>
        </div>

        <div className="grid gap-4 sm:grid-cols-3">
          <div><label className="text-sm mb-1 block">الاسم (اختياري)</label><Input placeholder="الاسم الكامل" value={fullName} onChange={(e) => setFullName(e.target.value)} /></div>
          <div><label className="text-sm mb-1 block">رقم التلفون (اختياري)</label><Input placeholder="+20 100 000 0000" value={phone} dir="ltr" onChange={(e) => setPhone(e.target.value)} /></div>
          <div><label className="text-sm mb-1 block">البلد (اختياري)</label><Input placeholder="مصر" value={country} onChange={(e) => setCountry(e.target.value)} /></div>
        </div>

        <div className="space-y-4">
          <h3 className="text-sm font-medium">المنصات التي ستنشر عليها</h3>
          {platforms.map((p, i) => (
            <div key={i} className="flex gap-2 items-start">
              <div className="flex-1 grid gap-2 sm:grid-cols-2">
                <Input placeholder="اسم المنصة (مثال: يوتيوب)" value={p.name} onChange={(e) => updatePlatform(i, "name", e.target.value)} />
                <Input placeholder="رابط الصفحة أو الحساب" value={p.url} dir="ltr" onChange={(e) => updatePlatform(i, "url", e.target.value)} />
              </div>
              <Button variant="ghost" size="icon" className="h-10 w-10 shrink-0 mt-0" onClick={() => removePlatform(i)}>
                <Trash2 className="h-4 w-4 text-destructive" />
              </Button>
            </div>
          ))}
          <Button variant="outline" size="sm" onClick={addPlatform}><PlusCircle className="h-4 w-4 ml-2" />إضافة منصة</Button>
        </div>

        <div className="border-t pt-4 space-y-4">
          <h3 className="text-sm font-medium">وسائل الدفع</h3>
          <div className="flex flex-wrap gap-4">
            <label className="flex items-center gap-2 cursor-pointer"><input type="checkbox" checked={usePaypal} onChange={(e) => setUsePaypal(e.target.checked)} className="h-4 w-4" /><span className="text-sm">PayPal</span></label>
            <label className="flex items-center gap-2 cursor-pointer"><input type="checkbox" checked={useCrypto} onChange={(e) => setUseCrypto(e.target.checked)} className="h-4 w-4" /><span className="text-sm">عملات رقمية</span></label>
            <label className="flex items-center gap-2 cursor-pointer"><input type="checkbox" checked={useContact} onChange={(e) => setUseContact(e.target.checked)} className="h-4 w-4" /><span className="text-sm">تواصل معنا</span></label>
          </div>
          {usePaypal && <div><label className="text-sm mb-1 block">إيميل PayPal</label><Input placeholder="your@email.com" value={paypalEmail} dir="ltr" onChange={(e) => setPaypalEmail(e.target.value)} /></div>}
          {useCrypto && (
            <div className="space-y-3">
              <div className="grid gap-3 sm:grid-cols-3">
                <div><label className="text-sm mb-1 block">العملة</label>
                  <select className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={cryptoType} onChange={(e) => { setCryptoType(e.target.value); setCryptoNetwork("") }}>
                    <option value="">-- اختر --</option><option value="USDT">USDT</option><option value="USDC">USDC</option><option value="BTC">BTC</option>
                  </select></div>
                <div><label className="text-sm mb-1 block">الشبكة</label>
                  <select className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={cryptoNetwork} onChange={(e) => setCryptoNetwork(e.target.value)} disabled={!cryptoType}>
                    <option value="">-- اختر --</option>{cryptoType && networks[cryptoType]?.map((n) => (<option key={n} value={n}>{n}</option>))}
                  </select></div>
                <div><label className="text-sm mb-1 block">عنوان المحفظة</label><Input placeholder={cryptoType === "BTC" ? "bc1..." : "0x..."} value={cryptoAddress} dir="ltr" onChange={(e) => setCryptoAddress(e.target.value)} /></div>
              </div>
            </div>
          )}
          {useContact && <p className="text-sm text-muted-foreground">سيتم التواصل معك لترتيب وسيلة الدفع المناسبة</p>}
        </div>

        <div>
          <label className="text-sm font-medium mb-1 block">ملاحظة (اختياري)</label>
          <textarea className="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="أي ملاحظة إضافية..." value={note} onChange={(e) => setNote(e.target.value)} />
        </div>

        {error && <p className="text-sm text-destructive">{error}</p>}
        <Button onClick={handleSubmit} disabled={isPending} className="w-full">
          {isPending ? "جارٍ إرسال الطلب..." : "تقديم الطلب"}
          {!isPending && <Send className="h-4 w-4 mr-2" />}
        </Button>
      </CardContent>
    </Card>
  );
}

function PendingApplication({ app, onUpdatePayment, isPending }: { app: Application; onUpdatePayment: (d: Record<string, unknown>) => void; isPending: boolean }) {
  return (
    <div className="space-y-4">
      <Card className="border-amber-200 dark:border-amber-800">
        <CardContent className="p-6 text-center">
          <div className="h-16 w-16 rounded-full bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center mx-auto mb-4"><Clock className="h-8 w-8 text-amber-600" /></div>
          <h2 className="text-xl font-semibold mb-2">طلبك قيد المراجعة</h2>
          <p className="text-muted-foreground max-w-md mx-auto mb-4">تم استلام طلب انضمامك لبرنامج العمولة. سيقوم فريق الإدارة بمراجعته والرد عليك في أقرب وقت.</p>
          <div className="text-xs text-muted-foreground">تم التقديم: {formatRelativeDate(app.createdAt)}</div>
        </CardContent>
      </Card>
      {app.fullName && (
        <Card><CardContent className="p-4 text-sm space-y-1">
          {app.fullName && <p><span className="font-medium">الاسم:</span> {app.fullName}</p>}
          {app.phone && <p><span className="font-medium">التلفون:</span> {app.phone}</p>}
          {app.country && <p><span className="font-medium">البلد:</span> {app.country}</p>}
        </CardContent></Card>
      )}
      <Card><CardContent className="p-4">
        <PaymentMethodsForm paypalEmail={app.paypalEmail} cryptoType={app.cryptoType} cryptoAddress={app.cryptoAddress} cryptoNetwork={app.cryptoNetwork} contactForPayment={app.contactForPayment} onSave={onUpdatePayment} isPending={isPending} compact />
      </CardContent></Card>
    </div>
  );
}

function RejectedApplication({ app, onUpdatePayment, isPending, onReapply }: { app: Application; onUpdatePayment: (d: Record<string, unknown>) => void; isPending: boolean; onReapply: () => void }) {
  return (
    <div className="space-y-4">
      <Card className="border-destructive/20">
        <CardContent className="p-6 text-center">
          <div className="h-16 w-16 rounded-full bg-destructive/10 flex items-center justify-center mx-auto mb-4"><XCircle className="h-8 w-8 text-destructive" /></div>
          <h2 className="text-xl font-semibold mb-2">لم تتم الموافقة على طلبك</h2>
          {app.adminNote && <div className="bg-muted rounded-md p-3 mb-4 max-w-md mx-auto text-sm"><p className="font-medium mb-1">السبب:</p><p className="text-muted-foreground">{app.adminNote}</p></div>}
          <Button onClick={onReapply} variant="outline">إعادة التقديم</Button>
        </CardContent>
      </Card>
      <Card><CardContent className="p-4">
        <PaymentMethodsForm paypalEmail={app.paypalEmail} cryptoType={app.cryptoType} cryptoAddress={app.cryptoAddress} cryptoNetwork={app.cryptoNetwork} contactForPayment={app.contactForPayment} onSave={onUpdatePayment} isPending={isPending} compact />
      </CardContent></Card>
    </div>
  );
}

function ReportsSection({ links }: { links: AffiliateLink[] }) {
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [queryFrom, setQueryFrom] = useState("");
  const [queryTo, setQueryTo] = useState("");

  const { data: reportsResp, isLoading } = useQuery({
    queryKey: ["affiliates", "reports", queryFrom, queryTo],
    queryFn: () => api.get<{ data: ReportsData }>(`/affiliates/reports?from=${queryFrom}&to=${queryTo}`),
    enabled: links.length > 0,
  });

  const reports = reportsResp?.data;

  const applyFilter = () => { setQueryFrom(from); setQueryTo(to); };

  const exportCSV = () => {
    if (!reports) return;
    const rows = [
      ["المقياس", "القيمة"],
      ["إجمالي الزيارات", reports.totalClicks],
      ["إجمالي التحويلات", reports.totalConversions],
      ["معدل التحويل", `${reports.conversionRate}%`],
      ["إجمالي الأرباح", `$${reports.totalEarned}`],
      ["متوسط العمولة", `$${reports.avgCommission}`], [],
      ["المصدر", "الزيارات", "النسبة"],
      ...reports.sourceBreakdown.map((s: SourceItem) => [s.source, s.count, `${s.percentage}%`]), [],
      ["الجهاز", "الزيارات", "النسبة"],
      ...reports.deviceBreakdown.map((d: DeviceItem) => [d.device, d.count, `${d.percentage}%`]),
    ];
    const csv = rows.map((r) => r.join(",")).join("\n");
    const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = "affiliate-report.csv"; a.click();
    URL.revokeObjectURL(url);
  };

  const exportPDF = () => {
    if (!reports) return;
    const w = window.open("", "_blank");
    if (!w) return;
    const lines = [
      "<!DOCTYPE html><html dir='rtl'><head><meta charset='utf-8'><title>تقرير الأفلييت</title>",
      "<style>body{font-family:sans-serif;padding:20px;max-width:700px;margin:auto}",
      "table{width:100%;border-collapse:collapse;margin:15px 0}",
      "th,td{border:1px solid #ddd;padding:8px;text-align:center}th{background:#f5f5f5}",
      "h2{color:#333;border-bottom:2px solid #10b981;padding-bottom:5px}</style></head><body>",
      `<h1>تقرير التسويق بالعمولة</h1>`,
      `<p>الفترة: ${queryFrom || "الكل"} → ${queryTo || "الكل"}</p>`,
      "<h2>ملخص الأداء</h2><table><tr><th>المقياس</th><th>القيمة</th></tr>",
      `<tr><td>إجمالي الزيارات</td><td>${reports.totalClicks}</td></tr>`,
      `<tr><td>إجمالي التحويلات</td><td>${reports.totalConversions}</td></tr>`,
      `<tr><td>معدل التحويل</td><td>${reports.conversionRate}%</td></tr>`,
      `<tr><td>إجمالي الأرباح</td><td>$${reports.totalEarned}</td></tr>`,
      `<tr><td>متوسط العمولة</td><td>$${reports.avgCommission}</td></tr>`,
      "</table>",
      "<h2>مصدر الزيارات</h2><table><tr><th>المصدر</th><th>الزيارات</th><th>النسبة</th></tr>",
      ...reports.sourceBreakdown.map((s: SourceItem) => `<tr><td>${s.source}</td><td>${s.count}</td><td>${s.percentage}%</td></tr>`),
      "</table>",
      "<h2>الأجهزة</h2><table><tr><th>الجهاز</th><th>الزيارات</th><th>النسبة</th></tr>",
      ...reports.deviceBreakdown.map((d: DeviceItem) => `<tr><td>${d.device}</td><td>${d.count}</td><td>${d.percentage}%</td></tr>`),
      "</table></body></html>",
    ];
    w.document.write(lines.join("")); w.document.close(); w.focus();
    setTimeout(() => w.print(), 500);
  };

  return (
    <Card>
      <CardContent className="p-6">
        <div className="flex items-center gap-3 mb-6">
          <TrendingUp className="h-5 w-5 text-primary" />
          <h2 className="text-xl font-semibold">التقارير</h2>
        </div>

        <div className="flex flex-wrap items-end gap-3 mb-6 p-4 bg-muted/30 rounded-lg">
          <div><label className="text-xs font-medium mb-1 block text-muted-foreground">من</label><Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="w-40" dir="ltr" /></div>
          <div><label className="text-xs font-medium mb-1 block text-muted-foreground">إلى</label><Input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="w-40" dir="ltr" /></div>
          <Button size="sm" onClick={applyFilter}><Calendar className="h-4 w-4 ml-1" />تطبيق</Button>
          {(queryFrom || queryTo) && <Button variant="ghost" size="sm" onClick={() => { setFrom(""); setTo(""); setQueryFrom(""); setQueryTo(""); }}>إعادة تعيين</Button>}
        </div>

        {isLoading ? (
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[1,2,3,4,5].map((i) => <Skeleton key={i} className="h-24" />)}</div>
        ) : reports ? (
          <>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5 mb-6">
              <ReportCard label="إجمالي الزيارات" value={reports.totalClicks.toLocaleString()} icon={MousePointerClick} color="text-purple-600 bg-purple-100 dark:bg-purple-900/30" />
              <ReportCard label="إجمالي التحويلات" value={reports.totalConversions.toLocaleString()} icon={TrendingUp} color="text-emerald-600 bg-emerald-100 dark:bg-emerald-900/30" />
              <ReportCard label="معدل التحويل" value={`${reports.conversionRate}%`} icon={Link2} color="text-blue-600 bg-blue-100 dark:bg-blue-900/30" />
              <ReportCard label="إجمالي الأرباح" value={formatCurrency(reports.totalEarned, "USD")} icon={DollarSign} color="text-amber-600 bg-amber-100 dark:bg-amber-900/30" />
              <ReportCard label="متوسط العمولة" value={formatCurrency(reports.avgCommission, "USD")} icon={DollarSign} color="text-rose-600 bg-rose-100 dark:bg-rose-900/30" />
            </div>

            <div className="grid gap-6 md:grid-cols-2 mb-6">
              <Card><CardContent className="p-4">
                <h3 className="font-semibold text-sm mb-3 flex items-center gap-2"><MousePointerClick className="h-4 w-4 text-muted-foreground" />مصدر الزيارات</h3>
                <div className="space-y-2">
                  {reports.sourceBreakdown.map((s: SourceItem) => (<BreakdownBar key={s.source} label={sourceLabel(s.source)} percentage={s.percentage} value={s.count} />))}
                  {reports.sourceBreakdown.length === 0 && <p className="text-sm text-muted-foreground">لا توجد بيانات</p>}
                </div>
              </CardContent></Card>
              <Card><CardContent className="p-4">
                <h3 className="font-semibold text-sm mb-3 flex items-center gap-2"><Monitor className="h-4 w-4 text-muted-foreground" />الأجهزة</h3>
                <div className="space-y-2">
                  {reports.deviceBreakdown.map((d: DeviceItem) => (<BreakdownBar key={d.device} label={deviceLabel(d.device)} percentage={d.percentage} value={d.count} />))}
                  {reports.deviceBreakdown.length === 0 && <p className="text-sm text-muted-foreground">لا توجد بيانات</p>}
                </div>
              </CardContent></Card>
            </div>

            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={exportCSV}><Download className="h-4 w-4 ml-1" />تصدير CSV</Button>
              <Button variant="outline" size="sm" onClick={exportPDF}><Download className="h-4 w-4 ml-1" />تصدير PDF</Button>
            </div>
          </>
        ) : null}
      </CardContent>
    </Card>
  );
}

interface SourceItem { source: string; count: number; percentage: number; }
interface DeviceItem { device: string; count: number; percentage: number; }
interface ReportsData {
  totalClicks: number; totalConversions: number; conversionRate: number;
  totalEarned: number; avgCommission: number;
  sourceBreakdown: SourceItem[]; deviceBreakdown: DeviceItem[];
}

const sourceLabels: Record<string, string> = {
  facebook: "فيسبوك", twitter: "تويتر", instagram: "انستغرام", linkedin: "لينكد إن",
  youtube: "يوتيوب", tiktok: "تيك توك", pinterest: "بينتريست", whatsapp: "واتساب",
  telegram: "تيليغرام", google: "قوقل", search: "محرك بحث", email: "بريد إلكتروني",
  reddit: "ريديت", discord: "ديسكورد", direct: "مباشر", other: "أخرى", unknown: "غير معروف",
};
function sourceLabel(s: string) { return sourceLabels[s] || s; }

const deviceLabels: Record<string, string> = { mobile: "جوال", desktop: "حاسوب", tablet: "جهاز لوحي" };
function deviceLabel(d: string) { return deviceLabels[d] || d; }

function ReportCard({ label, value, icon: Icon, color }: { label: string; value: string; icon: any; color: string }) {
  return (
    <Card><CardContent className="p-4 flex items-center gap-3">
      <div className={`h-10 w-10 rounded-lg flex items-center justify-center shrink-0 ${color}`}><Icon className="h-5 w-5" /></div>
      <div className="min-w-0"><p className="text-lg font-bold">{value}</p><p className="text-xs text-muted-foreground truncate">{label}</p></div>
    </CardContent></Card>
  );
}

function BreakdownBar({ label, percentage, value }: { label: string; percentage: number; value: number }) {
  return (
    <div>
      <div className="flex items-center justify-between text-sm mb-1">
        <span className="text-muted-foreground">{label}</span>
        <span className="font-medium">{value} ({percentage}%)</span>
      </div>
      <div className="h-2 bg-muted rounded-full overflow-hidden">
        <div className="h-full bg-primary rounded-full transition-all" style={{ width: `${Math.max(percentage, 2)}%` }} />
      </div>
    </div>
  );
}

function AutoGeneratedLink({ links, copyToClipboard, copiedCode }: {
  links: AffiliateLink[]; copyToClipboard: (text: string) => void; copiedCode: string | null;
}) {
  const autoLink = links.find((l) => l.isAutoGenerated);
  if (!autoLink) return null;
  const refUrl = `${absoluteUrl("/")}?ref=${autoLink.code}`;

  return (
    <Card className="border-emerald-200 dark:border-emerald-800 bg-gradient-to-l from-emerald-50/50 to-transparent dark:from-emerald-950/20">
      <CardContent className="p-6">
        <div className="flex items-center gap-3 mb-3">
          <div className="h-8 w-8 rounded-full bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center"><UserCheck className="h-4 w-4 text-emerald-600" /></div>
          <div><h3 className="font-semibold">رابطك التابع</h3><p className="text-xs text-muted-foreground">هذا الرابط التلقائي خاص بك، شاركه لبدء الربح</p></div>
        </div>
        <div className="flex items-center gap-2 bg-background rounded-md border p-3">
          <code className="flex-1 text-sm font-mono truncate" dir="ltr">{refUrl}</code>
          <Button variant="ghost" size="icon" className="h-8 w-8 shrink-0" onClick={() => copyToClipboard(refUrl)}>
            {copiedCode === refUrl ? <Check className="h-4 w-4 text-emerald-500" /> : <Copy className="h-4 w-4" />}
          </Button>
          <code className="text-xs font-mono bg-muted px-2 py-0.5 rounded shrink-0" dir="ltr">{autoLink.code}</code>
        </div>
      </CardContent>
    </Card>
  );
}
