export const EVENTS = {
  USER: {
    REGISTERED: 'user.registered',
    LOGGED_IN: 'user.logged_in',
    LOGGED_OUT: 'user.logged_out',
    EMAIL_VERIFIED: 'user.email_verified',
    PASSWORD_RESET: 'user.password_reset',
    PROFILE_UPDATED: 'user.profile_updated',
    DELETED: 'user.deleted',
    BANNED: 'user.banned',
    SUSPENDED: 'user.suspended',
  },
  TOOL: {
    CREATED: 'tool.created',
    UPDATED: 'tool.updated',
    DELETED: 'tool.deleted',
    APPROVED: 'tool.approved',
    REJECTED: 'tool.rejected',
    FEATURED: 'tool.featured',
    SPONSORED: 'tool.sponsored',
    REPORTED: 'tool.reported',
    CLAIMED: 'tool.claimed',
    VIEWED: 'tool.viewed',
    CLICKED: 'tool.clicked',
  },
  REVIEW: {
    CREATED: 'review.created',
    UPDATED: 'review.updated',
    DELETED: 'review.deleted',
    FLAGGED: 'review.flagged',
  },
  PAYMENT: {
    SUCCEEDED: 'payment.succeeded',
    FAILED: 'payment.failed',
    REFUNDED: 'payment.refunded',
    SUBSCRIPTION_CREATED: 'subscription.created',
    SUBSCRIPTION_CANCELED: 'subscription.canceled',
    SUBSCRIPTION_EXPIRED: 'subscription.expired',
  },
  NOTIFICATION: {
    SENT: 'notification.sent',
    READ: 'notification.read',
  },
  SYSTEM: {
    ERROR: 'system.error',
    WARNING: 'system.warning',
    INFO: 'system.info',
  },
} as const;
